app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_default_save:
    pattern:  /saveLogs
    defaults: { _controller: AppBundle:Default:saveLog, _format: ~ }
    requirements:
        _method: POST
